services:
    - docker

before_install:
    - docker --version

addons:
  apt:
    packages:
      - docker-ce

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="mmornati/docker-ghostblog"
    - if [ -n "$TRAVIS_TAG" ]; then
      image="$image:$TRAVIS_TAG";
      fi
script:
    - docker build -t "$image" .
    - docker run -d --name blogtest -p 2368:2368 -e NODE_ENV=production "$image"
    - until nc -z $(docker inspect --format='{{.NetworkSettings.IPAddress}}' blogtest) 2368; do
          echo "waiting for ghostblog container...";
          sleep 2;
      done
    - echo "GhostTest available..."
    - official-images/test/run.sh "$image"
    - curl http://localhost:2368 | grep "The professional publishing platform"

after_script:
    - docker inspect "$image"    
    - docker images
    - docker logs blogtest
    - docker stop blogtest
    - docker rm blogtest

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then 
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$image";
    fi
